version: '3.6'

services:

  # Backend API
  amemegeneratorapi:
    container_name: backend
    # image: node:8.11.1
    build: ./
    command: npm start
    working_dir: /usr/src/amemegeneratorapi
    environment:
     #POSTGRES_URI: postgres://postgres:adarshserver1@postgres:5432/template0
     # POSTGRES_USER: postgres
     # POSTGRES_PASSWORD: adarshserver1
      POSTGRES_DB: process.env.DATABASE_URL
      POSTGRES_HOST: true
    ports:
      - "process.env.PORT:process.env.PORT"
    volumes:
      - ./:/usr/src/amemegeneratorapi

  # Postgres
  postgres:
    #container_name: postgres
    environment:
      #POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: adarshserver1
      POSTGRES_DB: process.env.DATABASE_URL
      POSTGRES_HOST: ssl
    build: ./postgres
    ports:
      - "process.env.PORT:process.env.PORT"
